#pragma kernel CalculateAmplitudes

#include "Assets/ShaderLibrary/complex.hlsl"

RWTexture2D<complex> Dx_Dz;
RWTexture2D<complex> Dy_Dxz;
RWTexture2D<complex> Dyx_Dyz;
RWTexture2D<complex> Dxx_Dzz;

Texture2D<complex2> H0;
// wave vector x, 1 / wave magnitude, wave vector z, frequency
Texture2D<float4> WavesData;
float Time;

[numthreads(8,8,1)]
void CalculateAmplitudes(uint3 id : SV_DispatchThreadID)
{
	float4 wave = WavesData[id.xy];
	float phase = wave.w * Time;
	complex exponent = complex_euler(phase);
	complex h = complex_add(complex_mul(H0[id.xy].xy, exponent), complex_mul(H0[id.xy].zw, complex_conj(exponent)));
	complex ih = float2(-h.y, h.x);
	
	complex displacementX = ih * wave.x * wave.y;
	complex displacementY = h;
	complex displacementZ = ih * wave.z * wave.y;

	complex displacementX_dx = -h * wave.x * wave.x * wave.y;
	complex displacementY_dx = ih * wave.x;
	complex displacementZ_dx = -h * wave.x * wave.z * wave.y;

	complex displacementY_dz = ih * wave.z;
	complex displacementZ_dz = -h * wave.z * wave.z * wave.y;
	
	Dx_Dz[id.xy] = complex(displacementX.x - displacementZ.y, displacementX.y + displacementZ.x);
	Dy_Dxz[id.xy] = complex(displacementY.x - displacementZ_dx.y, displacementY.y + displacementZ_dx.x);
	Dyx_Dyz[id.xy] = complex(displacementY_dx.x - displacementY_dz.y, displacementY_dx.y + displacementY_dz.x);
	Dxx_Dzz[id.xy] = complex(displacementX_dx.x - displacementZ_dz.y, displacementX_dx.y + displacementZ_dz.x);
}
