#pragma kernel CalculateInitialSpectrum
#pragma kernel CalculateConjugateSpectrum

#include "Assets/ShaderLibrary/complex.hlsl"

static const float PI = 3.141592653589793;

// H0, complex_conj(H0)
RWTexture2D<complex2> _H0;
RWTexture2D<complex> _H0K;

// wave vector x, 1 / wave magnitude, wave vector z, frequency
Texture2D<float4> _WavesData;
Texture2D<float> _SpectrumSamples;
Texture2D<complex> _Noise;

// Cascade
float _LengthScale;
float _CutoffHigh;
float _CutoffLow;

uint _Size;
float _GravityAcceleration;
float _Depth;

float FrequencyDerivative(float k, float g, float depth, float omega)
{
	float th = tanh(min(k * depth, 20));
	float ch = cosh(k * depth);
	return g * (depth * k / (ch * ch) + th) / omega / 2;
}

[numthreads(8, 8, 1)]
void CalculateInitialSpectrum(uint3 id : SV_DispatchThreadID)
{
	float deltaK = 2 * PI / _LengthScale;
    float2 k = _WavesData[id.xy].xz;
	float kLength = length(k);
    float kLengthRcp = _WavesData[id.xy].y;

	_H0K[id.xy] = 0;

	if (kLength <= _CutoffHigh && kLength >= _CutoffLow)
	{
		float omega = _WavesData[id.xy].w;
		float dOmegadk = FrequencyDerivative(kLength, _GravityAcceleration, _Depth, omega);

        float spectrumSample = _SpectrumSamples[id.xy].r;

		_H0K[id.xy] = _Noise[id.xy]
			* sqrt(2 * spectrumSample * abs(dOmegadk) / kLength * deltaK * deltaK);

		// TODO: 1 kernel taking -k either by sampling _WavesData and
		// _SpectrumSample with uint2((_Size - id.x) % _Size, (_Size - id.y) % _Size).
		// Should be faster to do 4 sampling instead of two dispatch/two kernel.
		// complex h0K = _Noise[id.xy]
		// * sqrt(2 * spectrumSample * abs(dOmegadk) / kLength * deltaK * deltaK);
		// complex h0MinusK = _Noise[uint2((_Size - id.x) % _Size, (_Size - id.y) % _Size)]
		// * sqrt(2 * _SpectrumSamples[uint2((_Size - id.x) % _Size, (_Size - id.y) % _Size)].r * abs(dOmegadk) / kLength * deltaK * deltaK);
		// _H0[id.xy] = complex2(h0K, complex_conj(h0MinusK));
	}
}


[numthreads(8, 8, 1)]
void CalculateConjugateSpectrum(uint3 id : SV_DispatchThreadID)
{
	complex h0K = _H0K[id.xy];
	complex h0MinusK = _H0K[uint2((_Size - id.x) % _Size, (_Size - id.y) % _Size)];
	_H0[id.xy] = complex2(h0K, complex_conj(h0MinusK));
}
