#pragma kernel FillResultTextures

RWTexture2D<float3> _Displacement;
RWTexture2D<float4> _Derivatives;
RWTexture2D<float4> _Turbulence;

Texture2D<float2> _Dx_Dz;
Texture2D<float2> _Dy_Dxz;
Texture2D<float2> _Dyx_Dyz;
Texture2D<float2> _Dxx_Dzz;

float _Lambda;
float _DeltaTime;

[numthreads(8, 8, 1)]
void FillResultTextures(uint3 id : SV_DispatchThreadID)
{
	float2 DxDz = _Dx_Dz[id.xy];
	float2 DyDxz = _Dy_Dxz[id.xy];
	float2 DyxDyz = _Dyx_Dyz[id.xy];
	float2 DxxDzz = _Dxx_Dzz[id.xy];
	
	_Displacement[id.xy] = float3(_Lambda * DxDz.x, DyDxz.x, _Lambda * DxDz.y);
	_Derivatives[id.xy] = float4(DyxDyz, DxxDzz * _Lambda);
	float jacobian = (1 + _Lambda * DxxDzz.x) * (1 + _Lambda * DxxDzz.y) - _Lambda * _Lambda * DyDxz.y * DyDxz.y;
	
	_Turbulence[id.xy] = _Turbulence[id.xy].r + _DeltaTime * 0.5 / max(jacobian, 0.5);
	_Turbulence[id.xy] = min(jacobian, _Turbulence[id.xy].r);
}
